/**
 * ISO 3166-1 alpha-2 country list
 * Prioritized countries first, then alphabetical
 */
export const COUNTRIES = [
  // Prioritized
  { code: "US", name: "United States" },
  { code: "CA", name: "Canada" },
  { code: "GB", name: "United Kingdom" },
  { code: "AU", name: "Australia" },
  // Alphabetical
  { code: "AF", name: "Afghanistan" },
  { code: "AL", name: "Albania" },
  { code: "DZ", name: "Algeria" },
  { code: "AD", name: "Andorra" },
  { code: "AO", name: "Angola" },
  { code: "AG", name: "Antigua and Barbuda" },
  { code: "AR", name: "Argentina" },
  { code: "AM", name: "Armenia" },
  { code: "AT", name: "Austria" },
  { code: "AZ", name: "Azerbaijan" },
  { code: "BS", name: "Bahamas" },
  { code: "BH", name: "Bahrain" },
  { code: "BD", name: "Bangladesh" },
  { code: "BB", name: "Barbados" },
  { code: "BY", name: "Belarus" },
  { code: "BE", name: "Belgium" },
  { code: "BZ", name: "Belize" },
  { code: "BJ", name: "Benin" },
  { code: "BT", name: "Bhutan" },
  { code: "BO", name: "Bolivia" },
  { code: "BA", name: "Bosnia and Herzegovina" },
  { code: "BW", name: "Botswana" },
  { code: "BR", name: "Brazil" },
  { code: "BN", name: "Brunei" },
  { code: "BG", name: "Bulgaria" },
  { code: "BF", name: "Burkina Faso" },
  { code: "BI", name: "Burundi" },
  { code: "CV", name: "Cabo Verde" },
  { code: "KH", name: "Cambodia" },
  { code: "CM", name: "Cameroon" },
  { code: "CF", name: "Central African Republic" },
  { code: "TD", name: "Chad" },
  { code: "CL", name: "Chile" },
  { code: "CN", name: "China" },
  { code: "CO", name: "Colombia" },
  { code: "KM", name: "Comoros" },
  { code: "CG", name: "Congo" },
  { code: "CD", name: "Congo (DRC)" },
  { code: "CR", name: "Costa Rica" },
  { code: "HR", name: "Croatia" },
  { code: "CU", name: "Cuba" },
  { code: "CY", name: "Cyprus" },
  { code: "CZ", name: "Czechia" },
  { code: "CI", name: "Cote d'Ivoire" },
  { code: "DK", name: "Denmark" },
  { code: "DJ", name: "Djibouti" },
  { code: "DM", name: "Dominica" },
  { code: "DO", name: "Dominican Republic" },
  { code: "EC", name: "Ecuador" },
  { code: "EG", name: "Egypt" },
  { code: "SV", name: "El Salvador" },
  { code: "GQ", name: "Equatorial Guinea" },
  { code: "ER", name: "Eritrea" },
  { code: "EE", name: "Estonia" },
  { code: "SZ", name: "Eswatini" },
  { code: "ET", name: "Ethiopia" },
  { code: "FJ", name: "Fiji" },
  { code: "FI", name: "Finland" },
  { code: "FR", name: "France" },
  { code: "GA", name: "Gabon" },
  { code: "GM", name: "Gambia" },
  { code: "GE", name: "Georgia" },
  { code: "DE", name: "Germany" },
  { code: "GH", name: "Ghana" },
  { code: "GR", name: "Greece" },
  { code: "GD", name: "Grenada" },
  { code: "GT", name: "Guatemala" },
  { code: "GN", name: "Guinea" },
  { code: "GW", name: "Guinea-Bissau" },
  { code: "GY", name: "Guyana" },
  { code: "HT", name: "Haiti" },
  { code: "HN", name: "Honduras" },
  { code: "HK", name: "Hong Kong" },
  { code: "HU", name: "Hungary" },
  { code: "IS", name: "Iceland" },
  { code: "IN", name: "India" },
  { code: "ID", name: "Indonesia" },
  { code: "IR", name: "Iran" },
  { code: "IQ", name: "Iraq" },
  { code: "IE", name: "Ireland" },
  { code: "IL", name: "Israel" },
  { code: "IT", name: "Italy" },
  { code: "JM", name: "Jamaica" },
  { code: "JP", name: "Japan" },
  { code: "JO", name: "Jordan" },
  { code: "KZ", name: "Kazakhstan" },
  { code: "KE", name: "Kenya" },
  { code: "KI", name: "Kiribati" },
  { code: "KW", name: "Kuwait" },
  { code: "KG", name: "Kyrgyzstan" },
  { code: "LA", name: "Laos" },
  { code: "LV", name: "Latvia" },
  { code: "LB", name: "Lebanon" },
  { code: "LS", name: "Lesotho" },
  { code: "LR", name: "Liberia" },
  { code: "LY", name: "Libya" },
  { code: "LI", name: "Liechtenstein" },
  { code: "LT", name: "Lithuania" },
  { code: "LU", name: "Luxembourg" },
  { code: "MO", name: "Macau" },
  { code: "MG", name: "Madagascar" },
  { code: "MW", name: "Malawi" },
  { code: "MY", name: "Malaysia" },
  { code: "MV", name: "Maldives" },
  { code: "ML", name: "Mali" },
  { code: "MT", name: "Malta" },
  { code: "MH", name: "Marshall Islands" },
  { code: "MR", name: "Mauritania" },
  { code: "MU", name: "Mauritius" },
  { code: "MX", name: "Mexico" },
  { code: "FM", name: "Micronesia" },
  { code: "MD", name: "Moldova" },
  { code: "MC", name: "Monaco" },
  { code: "MN", name: "Mongolia" },
  { code: "ME", name: "Montenegro" },
  { code: "MA", name: "Morocco" },
  { code: "MZ", name: "Mozambique" },
  { code: "MM", name: "Myanmar" },
  { code: "NA", name: "Namibia" },
  { code: "NR", name: "Nauru" },
  { code: "NP", name: "Nepal" },
  { code: "NL", name: "Netherlands" },
  { code: "NZ", name: "New Zealand" },
  { code: "NI", name: "Nicaragua" },
  { code: "NE", name: "Niger" },
  { code: "NG", name: "Nigeria" },
  { code: "KP", name: "North Korea" },
  { code: "MK", name: "North Macedonia" },
  { code: "NO", name: "Norway" },
  { code: "OM", name: "Oman" },
  { code: "PK", name: "Pakistan" },
  { code: "PW", name: "Palau" },
  { code: "PS", name: "Palestine" },
  { code: "PA", name: "Panama" },
  { code: "PG", name: "Papua New Guinea" },
  { code: "PY", name: "Paraguay" },
  { code: "PE", name: "Peru" },
  { code: "PH", name: "Philippines" },
  { code: "PL", name: "Poland" },
  { code: "PT", name: "Portugal" },
  { code: "QA", name: "Qatar" },
  { code: "RO", name: "Romania" },
  { code: "RU", name: "Russia" },
  { code: "RW", name: "Rwanda" },
  { code: "KN", name: "Saint Kitts and Nevis" },
  { code: "LC", name: "Saint Lucia" },
  { code: "VC", name: "Saint Vincent and the Grenadines" },
  { code: "WS", name: "Samoa" },
  { code: "SM", name: "San Marino" },
  { code: "ST", name: "Sao Tome and Principe" },
  { code: "SA", name: "Saudi Arabia" },
  { code: "SN", name: "Senegal" },
  { code: "RS", name: "Serbia" },
  { code: "SC", name: "Seychelles" },
  { code: "SL", name: "Sierra Leone" },
  { code: "SG", name: "Singapore" },
  { code: "SK", name: "Slovakia" },
  { code: "SI", name: "Slovenia" },
  { code: "SB", name: "Solomon Islands" },
  { code: "SO", name: "Somalia" },
  { code: "ZA", name: "South Africa" },
  { code: "KR", name: "South Korea" },
  { code: "SS", name: "South Sudan" },
  { code: "ES", name: "Spain" },
  { code: "LK", name: "Sri Lanka" },
  { code: "SD", name: "Sudan" },
  { code: "SR", name: "Suriname" },
  { code: "SE", name: "Sweden" },
  { code: "CH", name: "Switzerland" },
  { code: "SY", name: "Syria" },
  { code: "TW", name: "Taiwan" },
  { code: "TJ", name: "Tajikistan" },
  { code: "TZ", name: "Tanzania" },
  { code: "TH", name: "Thailand" },
  { code: "TL", name: "Timor-Leste" },
  { code: "TG", name: "Togo" },
  { code: "TO", name: "Tonga" },
  { code: "TT", name: "Trinidad and Tobago" },
  { code: "TN", name: "Tunisia" },
  { code: "TR", name: "Turkey" },
  { code: "TM", name: "Turkmenistan" },
  { code: "TV", name: "Tuvalu" },
  { code: "UG", name: "Uganda" },
  { code: "UA", name: "Ukraine" },
  { code: "AE", name: "United Arab Emirates" },
  { code: "UY", name: "Uruguay" },
  { code: "UZ", name: "Uzbekistan" },
  { code: "VU", name: "Vanuatu" },
  { code: "VA", name: "Vatican City" },
  { code: "VE", name: "Venezuela" },
  { code: "VN", name: "Vietnam" },
  { code: "YE", name: "Yemen" },
  { code: "ZM", name: "Zambia" },
  { code: "ZW", name: "Zimbabwe" },
]

export type Country = (typeof COUNTRIES)[number]

/**
 * ISO 3166-1 alpha-2 → E.164 phone dial code
 * Used to enrich the DealMaker countries list with phone prefixes.
 */
export const PHONE_CODES: Record<string, string> = {
  AF: "+93", AL: "+355", DZ: "+213", AD: "+376", AO: "+244",
  AG: "+1268", AR: "+54", AM: "+374", AU: "+61", AT: "+43",
  AZ: "+994", BS: "+1242", BH: "+973", BD: "+880", BB: "+1246",
  BY: "+375", BE: "+32", BZ: "+501", BJ: "+229", BT: "+975",
  BO: "+591", BA: "+387", BW: "+267", BR: "+55", BN: "+673",
  BG: "+359", BF: "+226", BI: "+257", CV: "+238", KH: "+855",
  CM: "+237", CA: "+1", CF: "+236", TD: "+235", CL: "+56",
  CN: "+86", CO: "+57", KM: "+269", CG: "+242", CD: "+243",
  CR: "+506", HR: "+385", CU: "+53", CY: "+357", CZ: "+420",
  CI: "+225", DK: "+45", DJ: "+253", DM: "+1767", DO: "+1809",
  EC: "+593", EG: "+20", SV: "+503", GQ: "+240", ER: "+291",
  EE: "+372", SZ: "+268", ET: "+251", FJ: "+679", FI: "+358",
  FR: "+33", GA: "+241", GM: "+220", GE: "+995", DE: "+49",
  GH: "+233", GR: "+30", GD: "+1473", GT: "+502", GN: "+224",
  GW: "+245", GY: "+592", HT: "+509", HN: "+504", HK: "+852",
  HU: "+36", IS: "+354", IN: "+91", ID: "+62", IR: "+98",
  IQ: "+964", IE: "+353", IL: "+972", IT: "+39", JM: "+1876",
  JP: "+81", JO: "+962", KZ: "+7", KE: "+254", KI: "+686",
  KW: "+965", KG: "+996", LA: "+856", LV: "+371", LB: "+961",
  LS: "+266", LR: "+231", LY: "+218", LI: "+423", LT: "+370",
  LU: "+352", MO: "+853", MG: "+261", MW: "+265", MY: "+60",
  MV: "+960", ML: "+223", MT: "+356", MH: "+692", MR: "+222",
  MU: "+230", MX: "+52", FM: "+691", MD: "+373", MC: "+377",
  MN: "+976", ME: "+382", MA: "+212", MZ: "+258", MM: "+95",
  NA: "+264", NR: "+674", NP: "+977", NL: "+31", NZ: "+64",
  NI: "+505", NE: "+227", NG: "+234", KP: "+850", MK: "+389",
  NO: "+47", OM: "+968", PK: "+92", PW: "+680", PS: "+970",
  PA: "+507", PG: "+675", PY: "+595", PE: "+51", PH: "+63",
  PL: "+48", PT: "+351", QA: "+974", RO: "+40", RU: "+7",
  RW: "+250", KN: "+1869", LC: "+1758", VC: "+1784", WS: "+685",
  SM: "+378", ST: "+239", SA: "+966", SN: "+221", RS: "+381",
  SC: "+248", SL: "+232", SG: "+65", SK: "+421", SI: "+386",
  SB: "+677", SO: "+252", ZA: "+27", KR: "+82", SS: "+211",
  ES: "+34", LK: "+94", SD: "+249", SR: "+597", SE: "+46",
  CH: "+41", SY: "+963", TW: "+886", TJ: "+992", TZ: "+255",
  TH: "+66", TL: "+670", TG: "+228", TO: "+676", TT: "+1868",
  TN: "+216", TR: "+90", TM: "+993", TV: "+688", UG: "+256",
  UA: "+380", AE: "+971", GB: "+44", US: "+1", UY: "+598",
  UZ: "+998", VU: "+678", VA: "+379", VE: "+58", VN: "+84",
  YE: "+967", ZM: "+260", ZW: "+263",
}

/** A country entry enriched with its phone dial code */
export interface CountryWithPhone {
  isoCode: string   // e.g. "US"
  name: string      // e.g. "United States"
  phoneCode: string // e.g. "+1"
}

/**
 * Build a merged list from a DealMaker-sourced country list + PHONE_CODES.
 * Countries without a known phone code are omitted from the result.
 */
export function buildPhoneList(
  countries: { code: string; name: string }[]
): CountryWithPhone[] {
  return countries
    .filter((c) => !!PHONE_CODES[c.code])
    .map((c) => ({ isoCode: c.code, name: c.name, phoneCode: PHONE_CODES[c.code] }))
}

/** Static fallback phone list (used until DealMaker countries load) */
export const STATIC_PHONE_LIST: CountryWithPhone[] = buildPhoneList(COUNTRIES)

/**
 * Static states / provinces for key countries.
 * Used as a fallback when DealMaker does not return states for a country.
 */
export const STATIC_STATES: Record<string, { name: string; code: string }[]> = {
  US: [
    { name: "Alabama", code: "AL" }, { name: "Alaska", code: "AK" },
    { name: "Arizona", code: "AZ" }, { name: "Arkansas", code: "AR" },
    { name: "California", code: "CA" }, { name: "Colorado", code: "CO" },
    { name: "Connecticut", code: "CT" }, { name: "Delaware", code: "DE" },
    { name: "Florida", code: "FL" }, { name: "Georgia", code: "GA" },
    { name: "Hawaii", code: "HI" }, { name: "Idaho", code: "ID" },
    { name: "Illinois", code: "IL" }, { name: "Indiana", code: "IN" },
    { name: "Iowa", code: "IA" }, { name: "Kansas", code: "KS" },
    { name: "Kentucky", code: "KY" }, { name: "Louisiana", code: "LA" },
    { name: "Maine", code: "ME" }, { name: "Maryland", code: "MD" },
    { name: "Massachusetts", code: "MA" }, { name: "Michigan", code: "MI" },
    { name: "Minnesota", code: "MN" }, { name: "Mississippi", code: "MS" },
    { name: "Missouri", code: "MO" }, { name: "Montana", code: "MT" },
    { name: "Nebraska", code: "NE" }, { name: "Nevada", code: "NV" },
    { name: "New Hampshire", code: "NH" }, { name: "New Jersey", code: "NJ" },
    { name: "New Mexico", code: "NM" }, { name: "New York", code: "NY" },
    { name: "North Carolina", code: "NC" }, { name: "North Dakota", code: "ND" },
    { name: "Ohio", code: "OH" }, { name: "Oklahoma", code: "OK" },
    { name: "Oregon", code: "OR" }, { name: "Pennsylvania", code: "PA" },
    { name: "Rhode Island", code: "RI" }, { name: "South Carolina", code: "SC" },
    { name: "South Dakota", code: "SD" }, { name: "Tennessee", code: "TN" },
    { name: "Texas", code: "TX" }, { name: "Utah", code: "UT" },
    { name: "Vermont", code: "VT" }, { name: "Virginia", code: "VA" },
    { name: "Washington", code: "WA" }, { name: "West Virginia", code: "WV" },
    { name: "Wisconsin", code: "WI" }, { name: "Wyoming", code: "WY" },
    { name: "District of Columbia", code: "DC" },
  ],
  CA: [
    { name: "Alberta", code: "AB" }, { name: "British Columbia", code: "BC" },
    { name: "Manitoba", code: "MB" }, { name: "New Brunswick", code: "NB" },
    { name: "Newfoundland and Labrador", code: "NL" }, { name: "Northwest Territories", code: "NT" },
    { name: "Nova Scotia", code: "NS" }, { name: "Nunavut", code: "NU" },
    { name: "Ontario", code: "ON" }, { name: "Prince Edward Island", code: "PE" },
    { name: "Quebec", code: "QC" }, { name: "Saskatchewan", code: "SK" },
    { name: "Yukon", code: "YT" },
  ],
  AU: [
    { name: "Australian Capital Territory", code: "ACT" },
    { name: "New South Wales", code: "NSW" },
    { name: "Northern Territory", code: "NT" },
    { name: "Queensland", code: "QLD" },
    { name: "South Australia", code: "SA" },
    { name: "Tasmania", code: "TAS" },
    { name: "Victoria", code: "VIC" },
    { name: "Western Australia", code: "WA" },
  ],
  GB: [
    { name: "England", code: "ENG" },
    { name: "Northern Ireland", code: "NIR" },
    { name: "Scotland", code: "SCT" },
    { name: "Wales", code: "WLS" },
  ],
  DE: [
    { name: "Baden-Württemberg", code: "BW" }, { name: "Bavaria", code: "BY" },
    { name: "Berlin", code: "BE" }, { name: "Brandenburg", code: "BB" },
    { name: "Bremen", code: "HB" }, { name: "Hamburg", code: "HH" },
    { name: "Hesse", code: "HE" }, { name: "Lower Saxony", code: "NI" },
    { name: "Mecklenburg-Vorpommern", code: "MV" }, { name: "North Rhine-Westphalia", code: "NW" },
    { name: "Rhineland-Palatinate", code: "RP" }, { name: "Saarland", code: "SL" },
    { name: "Saxony", code: "SN" }, { name: "Saxony-Anhalt", code: "ST" },
    { name: "Schleswig-Holstein", code: "SH" }, { name: "Thuringia", code: "TH" },
  ],
  MX: [
    { name: "Aguascalientes", code: "AGU" }, { name: "Baja California", code: "BCN" },
    { name: "Baja California Sur", code: "BCS" }, { name: "Campeche", code: "CAM" },
    { name: "Chiapas", code: "CHP" }, { name: "Chihuahua", code: "CHH" },
    { name: "Ciudad de México", code: "CMX" }, { name: "Coahuila", code: "COA" },
    { name: "Colima", code: "COL" }, { name: "Durango", code: "DUR" },
    { name: "Guanajuato", code: "GUA" }, { name: "Guerrero", code: "GRO" },
    { name: "Hidalgo", code: "HID" }, { name: "Jalisco", code: "JAL" },
    { name: "México", code: "MEX" }, { name: "Michoacán", code: "MIC" },
    { name: "Morelos", code: "MOR" }, { name: "Nayarit", code: "NAY" },
    { name: "Nuevo León", code: "NLE" }, { name: "Oaxaca", code: "OAX" },
    { name: "Puebla", code: "PUE" }, { name: "Querétaro", code: "QUE" },
    { name: "Quintana Roo", code: "ROO" }, { name: "San Luis Potosí", code: "SLP" },
    { name: "Sinaloa", code: "SIN" }, { name: "Sonora", code: "SON" },
    { name: "Tabasco", code: "TAB" }, { name: "Tamaulipas", code: "TAM" },
    { name: "Tlaxcala", code: "TLA" }, { name: "Veracruz", code: "VER" },
    { name: "Yucatán", code: "YUC" }, { name: "Zacatecas", code: "ZAC" },
  ],
  NZ: [
    { name: "Auckland", code: "AUK" }, { name: "Bay of Plenty", code: "BOP" },
    { name: "Canterbury", code: "CAN" }, { name: "Gisborne", code: "GIS" },
    { name: "Hawke's Bay", code: "HKB" }, { name: "Manawatū-Whanganui", code: "MWT" },
    { name: "Marlborough", code: "MBH" }, { name: "Nelson", code: "NSN" },
    { name: "Northland", code: "NTL" }, { name: "Otago", code: "OTA" },
    { name: "Southland", code: "STL" }, { name: "Taranaki", code: "TKI" },
    { name: "Tasman", code: "TAS" }, { name: "Waikato", code: "WKO" },
    { name: "Wellington", code: "WGN" }, { name: "West Coast", code: "WTC" },
  ],
  ZA: [
    { name: "Eastern Cape", code: "EC" }, { name: "Free State", code: "FS" },
    { name: "Gauteng", code: "GP" }, { name: "KwaZulu-Natal", code: "KZN" },
    { name: "Limpopo", code: "LP" }, { name: "Mpumalanga", code: "MP" },
    { name: "North West", code: "NW" }, { name: "Northern Cape", code: "NC" },
    { name: "Western Cape", code: "WC" },
  ],
  AE: [
    { name: "Abu Dhabi", code: "AZ" }, { name: "Ajman", code: "AJ" },
    { name: "Dubai", code: "DU" }, { name: "Fujairah", code: "FU" },
    { name: "Ras Al Khaimah", code: "RK" }, { name: "Sharjah", code: "SH" },
    { name: "Umm Al Quwain", code: "UQ" },
  ],
  IN: [
    { name: "Andhra Pradesh", code: "AP" }, { name: "Arunachal Pradesh", code: "AR" },
    { name: "Assam", code: "AS" }, { name: "Bihar", code: "BR" },
    { name: "Chhattisgarh", code: "CG" }, { name: "Goa", code: "GA" },
    { name: "Gujarat", code: "GJ" }, { name: "Haryana", code: "HR" },
    { name: "Himachal Pradesh", code: "HP" }, { name: "Jharkhand", code: "JH" },
    { name: "Karnataka", code: "KA" }, { name: "Kerala", code: "KL" },
    { name: "Madhya Pradesh", code: "MP" }, { name: "Maharashtra", code: "MH" },
    { name: "Manipur", code: "MN" }, { name: "Meghalaya", code: "ML" },
    { name: "Mizoram", code: "MZ" }, { name: "Nagaland", code: "NL" },
    { name: "Odisha", code: "OD" }, { name: "Punjab", code: "PB" },
    { name: "Rajasthan", code: "RJ" }, { name: "Sikkim", code: "SK" },
    { name: "Tamil Nadu", code: "TN" }, { name: "Telangana", code: "TG" },
    { name: "Tripura", code: "TR" }, { name: "Uttar Pradesh", code: "UP" },
    { name: "Uttarakhand", code: "UK" }, { name: "West Bengal", code: "WB" },
    { name: "Delhi", code: "DL" },
  ],
}
